// This file is auto-generated by the Sitecore Content SDK.
// Below are built-in Content SDK imports neccessary for the import map
import {
  combineImportEntries,
  defaultImportEntries,
  ImportEntry,
} from '@sitecore-content-sdk/nextjs/codegen';
// end of built-in imports

import { jsx, jsxs, Fragment } from 'react/jsx-runtime';
import Head from 'next/head';
import client from 'lib/sitecore-client';
import { useCallback, useRef, useState, useEffect, useMemo } from 'react';
import React from 'react';
import { Placeholder, RichText, NextImage, Link, Text, useSitecore, withDatasourceCheck, CdpHelper, Image as Image_8a80e63291fea86e0744df19113dc44bec187216 } from '@sitecore-content-sdk/nextjs';
import PreviewSearchWidget from 'src/components/Search/PreviewSearch/PreviewSearch';
import { isSearchSDKEnabled } from 'src/services/SearchSDKService';
import PreviewSearchIcon from 'src/components/Search/PreviewSearch/PreviewSearchIcon';
import ClickOutside from 'src/hooks/ClickOutside';
import { useRouter } from 'next/router';
import Image from 'next/image';
import * as FEAAS from '@sitecore-feaas/clientside/react';
import nextConfig from 'next.config';
import { pageView, event } from '@sitecore-content-sdk/events';
import config from 'sitecore.config';
import { useI18n } from 'next-localization';
import { useSearch } from '@sitecore-content-sdk/nextjs/search';
import { cn } from 'lib/utils';
import { SearchEmptyResults } from 'src/components/search-experience/search-components/SearchEmptyResults';
import { SearchError } from 'src/components/search-experience/search-components/SearchError';
import { SearchItem } from 'src/components/search-experience/search-components/SearchItem/index';
import { SearchSkeletonItem } from 'src/components/search-experience/search-components/SearchSkeletonItem';
import { SearchPagination } from 'src/components/search-experience/search-components/SearchPagination';
import { SearchInput } from 'src/components/search-experience/search-components/SearchInput';
import { useEvent } from 'src/components/search-experience/search-components/useEvent';
import { useSearchField } from 'src/components/search-experience/search-components/useSearchField';
import { useParams } from 'src/components/search-experience/search-components/useParams';
import { DICTIONARY_KEYS, gridColsClass, DEFAULT_PAGE_SIZE, DEBOUNCE_TIME } from 'src/components/search-experience/search-components/constants';
import { useRouter as useRouter_718da64eaca4c1615fa5f1603d6d6260be2e7c90 } from 'src/components/search-experience/search-components/useRouter';
import { useDebouncedCallback } from 'src/components/search-experience/search-components/useDebounce';
import { ItemCardFrame, ItemListFrame } from 'src/components/search-experience/search-components/SearchItemCommon';
import { SearchItemTitle } from 'src/components/search-experience/search-components/SearchItem/SearchItemTitle';
import { SearchItemSummary } from 'src/components/search-experience/search-components/SearchItem/SearchItemSummary';
import { SearchItemLink } from 'src/components/search-experience/search-components/SearchItem/SearchItemLink';
import { SearchItemCategory } from 'src/components/search-experience/search-components/SearchItem/SearchItemCategory';
import { SearchItemTags } from 'src/components/search-experience/search-components/SearchItem/SearchItemTags';
import { SearchItemImage } from 'src/components/search-experience/search-components/SearchItem/SearchItemImage';
import { Presence, ArticleCard, PreviewSearch } from '@sitecore-search/ui';
import { WidgetDataType, usePreviewSearch, widget, PageController } from '@sitecore-search/react';
import Spinner from 'src/components/Search/components/Spinner/Spinner';
import useVisibility from 'src/hooks/useVisibility';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Autoplay, EffectCoverflow, Pagination, Navigation } from 'swiper/modules';
import { CountUp } from 'components/NonSitecore/CountUp';
import { DottedAccent } from 'components/NonSitecore/DottedAccent';
import { ParallaxBackgroundImage } from 'components/NonSitecore/ParallaxBackgroundImage';
import Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 from 'next/link';
import { FacebookIcon, FacebookShareButton, LinkedinIcon, LinkedinShareButton, TwitterIcon, TwitterShareButton } from 'react-share';
import { ParallaxBanner, useParallax, Parallax } from 'react-scroll-parallax';
import { IconAccent } from 'components/NonSitecore/IconAccent';

const importMap = [
  {
    module: 'react/jsx-runtime',
    exports: [
      { name: 'jsx', value: jsx },
      { name: 'jsxs', value: jsxs },
      { name: 'Fragment', value: Fragment },
    ]
  },
  {
    module: 'next/head',
    exports: [
      { name: 'default', value: Head },
    ]
  },
  {
    module: 'lib/sitecore-client',
    exports: [
      { name: 'default', value: client },
    ]
  },
  {
    module: 'react',
    exports: [
      { name: 'useCallback', value: useCallback },
      { name: 'useRef', value: useRef },
      { name: 'useState', value: useState },
      { name: 'useEffect', value: useEffect },
      { name: 'useMemo', value: useMemo },
      { name: 'default', value: React },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs',
    exports: [
      { name: 'Placeholder', value: Placeholder },
      { name: 'RichText', value: RichText },
      { name: 'NextImage', value: NextImage },
      { name: 'Link', value: Link },
      { name: 'Text', value: Text },
      { name: 'useSitecore', value: useSitecore },
      { name: 'withDatasourceCheck', value: withDatasourceCheck },
      { name: 'CdpHelper', value: CdpHelper },
      { name: 'Image', value: Image_8a80e63291fea86e0744df19113dc44bec187216 },
    ]
  },
  {
    module: 'src/components/Search/PreviewSearch/PreviewSearch',
    exports: [
      { name: 'default', value: PreviewSearchWidget },
    ]
  },
  {
    module: 'src/services/SearchSDKService',
    exports: [
      { name: 'isSearchSDKEnabled', value: isSearchSDKEnabled },
    ]
  },
  {
    module: 'src/components/Search/PreviewSearch/PreviewSearchIcon',
    exports: [
      { name: 'default', value: PreviewSearchIcon },
    ]
  },
  {
    module: 'src/hooks/ClickOutside',
    exports: [
      { name: 'default', value: ClickOutside },
    ]
  },
  {
    module: 'next/router',
    exports: [
      { name: 'useRouter', value: useRouter },
    ]
  },
  {
    module: 'next/image',
    exports: [
      { name: 'default', value: Image },
    ]
  },
  {
    module: '@sitecore-feaas/clientside/react',
    exports: [
      { name: '*', value: FEAAS },
    ]
  },
  {
    module: 'next.config',
    exports: [
      { name: 'default', value: nextConfig },
    ]
  },
  {
    module: '@sitecore-content-sdk/events',
    exports: [
      { name: 'pageView', value: pageView },
      { name: 'event', value: event },
    ]
  },
  {
    module: 'sitecore.config',
    exports: [
      { name: 'default', value: config },
    ]
  },
  {
    module: 'next-localization',
    exports: [
      { name: 'useI18n', value: useI18n },
    ]
  },
  {
    module: '@sitecore-content-sdk/nextjs/search',
    exports: [
      { name: 'useSearch', value: useSearch },
    ]
  },
  {
    module: 'lib/utils',
    exports: [
      { name: 'cn', value: cn },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchEmptyResults',
    exports: [
      { name: 'SearchEmptyResults', value: SearchEmptyResults },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchError',
    exports: [
      { name: 'SearchError', value: SearchError },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/index',
    exports: [
      { name: 'SearchItem', value: SearchItem },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchSkeletonItem',
    exports: [
      { name: 'SearchSkeletonItem', value: SearchSkeletonItem },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchPagination',
    exports: [
      { name: 'SearchPagination', value: SearchPagination },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchInput',
    exports: [
      { name: 'SearchInput', value: SearchInput },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useEvent',
    exports: [
      { name: 'useEvent', value: useEvent },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useSearchField',
    exports: [
      { name: 'useSearchField', value: useSearchField },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useParams',
    exports: [
      { name: 'useParams', value: useParams },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/constants',
    exports: [
      { name: 'DICTIONARY_KEYS', value: DICTIONARY_KEYS },
      { name: 'gridColsClass', value: gridColsClass },
      { name: 'DEFAULT_PAGE_SIZE', value: DEFAULT_PAGE_SIZE },
      { name: 'DEBOUNCE_TIME', value: DEBOUNCE_TIME },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useRouter',
    exports: [
      { name: 'useRouter', value: useRouter_718da64eaca4c1615fa5f1603d6d6260be2e7c90 },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/useDebounce',
    exports: [
      { name: 'useDebouncedCallback', value: useDebouncedCallback },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItemCommon',
    exports: [
      { name: 'ItemCardFrame', value: ItemCardFrame },
      { name: 'ItemListFrame', value: ItemListFrame },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemTitle',
    exports: [
      { name: 'SearchItemTitle', value: SearchItemTitle },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemSummary',
    exports: [
      { name: 'SearchItemSummary', value: SearchItemSummary },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemLink',
    exports: [
      { name: 'SearchItemLink', value: SearchItemLink },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemCategory',
    exports: [
      { name: 'SearchItemCategory', value: SearchItemCategory },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemTags',
    exports: [
      { name: 'SearchItemTags', value: SearchItemTags },
    ]
  },
  {
    module: 'src/components/search-experience/search-components/SearchItem/SearchItemImage',
    exports: [
      { name: 'SearchItemImage', value: SearchItemImage },
    ]
  },
  {
    module: '@sitecore-search/ui',
    exports: [
      { name: 'Presence', value: Presence },
      { name: 'ArticleCard', value: ArticleCard },
      { name: 'PreviewSearch', value: PreviewSearch },
    ]
  },
  {
    module: '@sitecore-search/react',
    exports: [
      { name: 'WidgetDataType', value: WidgetDataType },
      { name: 'usePreviewSearch', value: usePreviewSearch },
      { name: 'widget', value: widget },
      { name: 'PageController', value: PageController },
    ]
  },
  {
    module: 'src/components/Search/components/Spinner/Spinner',
    exports: [
      { name: 'default', value: Spinner },
    ]
  },
  {
    module: 'src/hooks/useVisibility',
    exports: [
      { name: 'default', value: useVisibility },
    ]
  },
  {
    module: 'swiper/react',
    exports: [
      { name: 'Swiper', value: Swiper },
      { name: 'SwiperSlide', value: SwiperSlide },
    ]
  },
  {
    module: 'swiper/modules',
    exports: [
      { name: 'Autoplay', value: Autoplay },
      { name: 'EffectCoverflow', value: EffectCoverflow },
      { name: 'Pagination', value: Pagination },
      { name: 'Navigation', value: Navigation },
    ]
  },
  {
    module: 'components/NonSitecore/CountUp',
    exports: [
      { name: 'CountUp', value: CountUp },
    ]
  },
  {
    module: 'components/NonSitecore/DottedAccent',
    exports: [
      { name: 'DottedAccent', value: DottedAccent },
    ]
  },
  {
    module: 'components/NonSitecore/ParallaxBackgroundImage',
    exports: [
      { name: 'ParallaxBackgroundImage', value: ParallaxBackgroundImage },
    ]
  },
  {
    module: 'next/link',
    exports: [
      { name: 'default', value: Link_a258c208ba01265ca0aa9c7abae745cc7141aa63 },
    ]
  },
  {
    module: 'react-share',
    exports: [
      { name: 'FacebookIcon', value: FacebookIcon },
      { name: 'FacebookShareButton', value: FacebookShareButton },
      { name: 'LinkedinIcon', value: LinkedinIcon },
      { name: 'LinkedinShareButton', value: LinkedinShareButton },
      { name: 'TwitterIcon', value: TwitterIcon },
      { name: 'TwitterShareButton', value: TwitterShareButton },
    ]
  },
  {
    module: 'react-scroll-parallax',
    exports: [
      { name: 'ParallaxBanner', value: ParallaxBanner },
      { name: 'useParallax', value: useParallax },
      { name: 'Parallax', value: Parallax },
    ]
  },
  {
    module: 'components/NonSitecore/IconAccent',
    exports: [
      { name: 'IconAccent', value: IconAccent },
    ]
  }
] as ImportEntry[];

export default combineImportEntries(defaultImportEntries, importMap);
